---
- name: "Linux Lapa - Restart Dynatrace + Zabbix"
  hosts: aai
  gather_facts: true
  ignore_unreachable: true
  any_errors_fatal: false
  serial: 20
  vars_files:
    - ../../group_vars/all.yml
  roles:
    - restart-zabbix-oneagent-linux
